
import React from "react";
import Link from "next/link";
import ContactUs from "@/components/ContactUs";

export const metadata = {
  title: "Boutique Shop - Contact Us",
  description: "Generated by Boutique Shop - Contact Us",
};
const ContactPage = () => {
  return (
    <div className="min-h-screen">
      <div className="h-80" style={{backgroundImage: "url(https://i.postimg.cc/C105MhMS/image.png)",backgroundRepeat:"no-repeat",backgroundSize:'cover',backgroundPosition:'center'}}>
        <div className="container h-full flex flex-col gap-y-4 justify-center mx-auto px-4 ">
          <h1 className="text-5xl font-bold text-blue-800">Contact Us</h1>
          <p className="text-lg font-semibold text-blue-800"><Link className="text-blue-800" href='/'>Home</Link> / Contact Us</p>
        </div>
      </div>
      <div className="container mx-auto px-2">
        <ContactUs></ContactUs>
      </div>
    </div>
  );
};

export default ContactPage;
